## Loading the Dataset

The dataset is loaded into a pandas DataFrame for exploration.

The file uses comma-separated values, and the first row contains the column names. Empty fields will be treated as missing values by pandas.

The target variable and input features will be selected after inspecting the dataset and verifying the meaning of the available columns.
**Dataset download link is attached in Readme**

In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv("../data/KOIdataset.txt")
df.head()

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra_str,dec_str,koi_kepmag,koi_kepmag_err
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,4.467,0.064,-0.096,0.927,0.105,-0.061,19h27m44.22s,+48d08m29.9s,15.347,NaN
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,4.467,0.064,-0.096,0.927,0.105,-0.061,19h27m44.22s,+48d08m29.9s,15.347,NaN
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,4.544,0.044,-0.176,0.868,0.233,-0.078,19h48m01.16s,+48d08m02.9s,15.436,NaN
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,4.564,0.053,-0.168,0.791,0.201,-0.067,19h02m08.31s,+48d17m06.8s,15.597,NaN
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,4.438,0.070,-0.210,1.046,0.334,-0.133,19h15m01.17s,+48d13m34.3s,15.509,NaN

## Checking for required columns
Verify whether the dataset contains the columns required for exoplanet classification and identify relevant measurements.
### Columns Being Investigated
- `koi_period`: Orbital period of the candidate.
- `koi_depth`: Depth of the transit signal.
- `koi_duration`: Duration of the transit.
- `koi_disposition`: Archive classification of the object.
- `koi_pdisposition`: Pipeline disposition of the object.

In [6]:
[col for col in df.columns if any(
    word in col.lower()
    for word in ["period", "depth", "duration", "disposition"]
)]

['koi_disposition',
 'koi_pdisposition',
 'koi_period',
 'koi_period_err1',
 'koi_period_err2',
 'koi_duration',
 'koi_duration_err1',
 'koi_duration_err2',
 'koi_depth',
 'koi_depth_err1',
 'koi_depth_err2']

## Initial Data Inspection

The DataFrame will be inspected to understand its dimensions, available columns, data types, and sample records.

At this stage, no target variable or feature set is selected. Columns with names such as `disposition` will be treated as possible outcome-related fields until their meanings are verified.

In [8]:
print("Number of rows in the dataset:", df.shape[0])
print("Number of columns in the dataset:", df.shape[1])
print("Shape of the dataset:", df.shape)
print("First 5 rows of the dataset:")
df.head()

Number of rows in the dataset: 9564
Number of columns in the dataset: 50
Shape of the dataset: (9564, 50)
First 5 rows of the dataset:

,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,...,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra_str,dec_str,koi_kepmag,koi_kepmag_err
0,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,4.467,0.064,-0.096,0.927,0.105,-0.061,19h27m44.22s,+48d08m29.9s,15.347,NaN
1,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,0,...,4.467,0.064,-0.096,0.927,0.105,-0.061,19h27m44.22s,+48d08m29.9s,15.347,NaN
2,10811496,K00753.01,NaN,CANDIDATE,CANDIDATE,0.000,0,0,0,0,...,4.544,0.044,-0.176,0.868,0.233,-0.078,19h48m01.16s,+48d08m02.9s,15.436,NaN
3,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,0,...,4.564,0.053,-0.168,0.791,0.201,-0.067,19h02m08.31s,+48d17m06.8s,15.597,NaN
4,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,0,...,4.438,0.070,-0.210,1.046,0.334,-0.133,19h15m01.17s,+48d13m34.3s,15.509,NaN

## Statistical Summary of columns :

In [9]:
print("Description of the numeric columns:")
df.describe()

Description of the numeric columns:

,kepid,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,...,koi_steff_err1,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,koi_kepmag,koi_kepmag_err
count,9.564000e+03,8054.000000,9564.000000,9564.000000,9564.000000,9564.000000,9564.000000,9110.000000,9110.000000,9564.000000,...,9096.000000,9081.000000,9201.000000,9096.000000,9096.000000,9201.000000,9096.000000,9096.000000,9563.000000,0.0
mean,7.690628e+06,0.480829,0.208595,0.232748,0.197512,0.120033,75.671358,0.002148,-0.002148,166.183251,...,144.635554,-162.265059,4.310157,0.120738,-0.143161,1.728712,0.362292,-0.394806,14.264606,NaN
std,2.653459e+06,0.476928,4.767290,0.422605,0.398142,0.325018,1334.744046,0.008236,0.008236,67.918960,...,47.052305,72.746348,0.432606,0.132837,0.085477,6.127185,0.930870,2.168213,1.385448,NaN
min,7.574500e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.241843,0.000000,-0.172500,120.515914,...,0.000000,-1762.000000,0.047000,0.000000,-1.207000,0.109000,0.000000,-116.137000,6.966000,NaN
25%,5.556034e+06,0.000000,0.000000,0.000000,0.000000,0.000000,2.733684,0.000005,-0.000276,132.761718,...,106.000000,-198.000000,4.218000,0.042000,-0.196000,0.829000,0.129000,-0.250000,13.440000,NaN
50%,7.906892e+06,0.334000,0.000000,0.000000,0.000000,0.000000,9.752831,0.000035,-0.000035,137.224595,...,157.000000,-160.000000,4.438000,0.070000,-0.128000,1.000000,0.251000,-0.111000,14.520000,NaN
75%,9.873066e+06,0.998000,0.000000,0.000000,0.000000,0.000000,40.715178,0.000276,-0.000005,170.694603,...,174.000000,-114.000000,4.543000,0.149000,-0.088000,1.345000,0.364000,-0.069000,15.322000,NaN
max,1.293514e+07,1.000000,465.000000,1.000000,1.000000,1.000000,129995.778400,0.172500,0.000000,1472.522306,...,676.000000,0.000000,5.364000,1.472000,0.000000,229.908000,33.091000,0.000000,20.003000,NaN

In [11]:
print("Description of the categorical columns:")
df.describe(include=["str"])

Description of the categorical columns:

,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_tce_delivname,ra_str,dec_str
count,9564,2748,9564,9564,9218,9564,9564
unique,9564,2748,3,2,3,8103,8144
top,K00752.01,Kepler-227 b,FALSE POSITIVE,FALSE POSITIVE,q1_q17_dr25_tce,19h37m21.23s,+50d20m11.5s
freq,1,1,4839,4847,8054,7,7

## Inspecting Possible Outcome Labels

The unique values and frequency counts of the possible outcome columns will be inspected before selecting a target variable.

This step helps identify the available classes and their distribution. No target variable is selected yet because the meanings of the columns must be verified first. Columns that encode outcomes should not be used as input features.

In [12]:
print("The values in the 'koi_disposition' column are:", df["koi_disposition"].value_counts(dropna=False))
print("The values in the 'koi_pdisposition' column are:", df["koi_pdisposition"].value_counts(dropna=False))

The values in the 'koi_disposition' column are: koi_disposition
FALSE POSITIVE    4839
CONFIRMED         2748
CANDIDATE         1977
Name: count, dtype: int64
The values in the 'koi_pdisposition' column are: koi_pdisposition
FALSE POSITIVE    4847
CANDIDATE         4717
Name: count, dtype: int64

## Observed Outcome Labels

The `koi_disposition` column contains three observed labels: `FALSE POSITIVE`, `CONFIRMED`, and `CANDIDATE`.

The `koi_pdisposition` column contains two observed labels: `FALSE POSITIVE` and `CANDIDATE`.

These columns appear to represent different outcome definitions or stages. Their exact meanings must be verified using the NASA Kepler Objects of Interest documentation before selecting a target variable.

Because both columns are outcome-related, they will be treated as possible sources of target leakage and will not automatically be used as input features.

## Checking Missing Values

Missing values can affect summary statistics, feature selection, and later model training.

The number of missing values in each column will be inspected before deciding which columns can be used. Missing-value handling will be based on the meaning and role of each column rather than applying one automatic rule to the entire dataset.

In [14]:
print("Checking for missing values in the dataset:")
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0].sort_values(ascending=False))

Checking for missing values in the dataset:
koi_teq_err1         9564
koi_teq_err2         9564
koi_kepmag_err       9564
kepler_name          6816
koi_score            1510
koi_steff_err2        483
koi_srad_err2         468
koi_srad_err1         468
koi_slogg_err1        468
koi_steff_err1        468
koi_slogg_err2        468
koi_period_err1       454
koi_period_err2       454
koi_time0bk_err1      454
koi_depth_err2        454
koi_time0bk_err2      454
koi_impact_err1       454
koi_depth_err1        454
koi_duration_err2     454
koi_impact_err2       454
koi_duration_err1     454
koi_steff             363
koi_teq               363
koi_prad_err1         363
koi_prad_err2         363
koi_prad              363
koi_depth             363
koi_impact            363
koi_model_snr         363
koi_srad              363
koi_slogg             363
koi_tce_delivname     346
koi_tce_plnt_num      346
koi_insol             321
koi_insol_err1        321
koi_insol_err2        321
koi_kepmag              1
dtype: int64

## Identifying Completely Empty Columns

Some columns contain missing values for every row, while others are only partially missing.

Columns that are completely empty cannot provide information for exploratory analysis or model training. They will be identified separately from partially missing columns. No columns will be removed until their names and meanings have been reviewed.

In [16]:
comletely_empty_cols = df.columns[df.isnull().all()]
print("Columns that are completely empty:", comletely_empty_cols.tolist())

Columns that are completely empty: ['koi_teq_err1', 'koi_teq_err2', 'koi_kepmag_err']

## Removing Completely Empty Columns

Three columns contain no observed values in any row. Since completely empty columns cannot contribute information to exploratory analysis or model training, they are excluded from a separate working DataFrame.

The original DataFrame is preserved so that preprocessing decisions remain transparent and reversible. Partially missing columns are not removed automatically.

In [18]:
df_clean=df.dropna(axis=1, how="all")
print("Shape of the dataset before cleaning:", df.shape)
print("Shape of the cleaned dataset:", df_clean.shape)
print("Columns that were removed due to being completely empty:")
print([col for col in df.columns if df[col].isnull().all() and col not in df_clean.columns])

Shape of the dataset before cleaning: (9564, 50)
Shape of the cleaned dataset: (9564, 47)
Columns that were removed due to being completely empty:
['koi_teq_err1', 'koi_teq_err2', 'koi_kepmag_err']